const express=require('express'); const db=require('../db'); const {authenticate,requireRole}=require('../middleware/auth'); const router=express.Router(); router.use(authenticate);
const withStatus=r=>{const paid=Number(r.advance_paid||0)+Number(r.settled_amount||0);const total=Number(r.total_amount||0);return {...r,paid_amount:paid,balance_due:Math.max(total-paid,0),status:paid<=0?'pending':paid>=total?'paid':'partial'}};
router.get('/',async(req,res,next)=>{try{const {category,vendor_id,from,to,search,status}=req.query;let q='SELECT * FROM expenses WHERE 1=1',p=[];const add=(s,v)=>{q+=' '+s.replace('?',`$${p.length+1}`);p.push(v)};if(category)add('AND category = ?',category);if(vendor_id)add('AND vendor_id = ?',vendor_id);if(from)add('AND date >= ?',from);if(to)add('AND date <= ?',to);if(search){const n=p.length+1;q+=` AND (description ILIKE $${n} OR notes ILIKE $${n} OR bill_no ILIKE $${n})`;p.push(`%${search}%`)}q+=' ORDER BY date DESC,id DESC';let rows=(await db.all(q,p)).map(withStatus);if(status)rows=rows.filter(r=>r.status===status);res.json(rows)}catch(e){next(e)}});
router.get('/:id',async(req,res,next)=>{try{const r=await db.get('SELECT * FROM expenses WHERE id=$1',[req.params.id]);if(!r)return res.status(404).json({error:'Expense not found.'});res.json(withStatus(r))}catch(e){next(e)}});
router.post('/',async(req,res,next)=>{try{const {vendor_id,category,description,date,total_amount,advance_paid,settled_amount,payment_mode,bill_no,notes}=req.body;if(!category||!description||!date||total_amount==null)return res.status(400).json({error:'category, description, date and total_amount are required.'});if(Number(total_amount)<0||Number(advance_paid||0)<0||Number(settled_amount||0)<0)return res.status(400).json({error:'Amounts cannot be negative.'});const r=await db.get(`INSERT INTO expenses (vendor_id,category,description,date,total_amount,advance_paid,settled_amount,payment_mode,bill_no,notes,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[vendor_id||null,category,description,date,total_amount,advance_paid||0,settled_amount||0,payment_mode||'Cash',bill_no||null,notes||null,req.user.id]);res.status(201).json(withStatus(r))}catch(e){next(e)}});
router.put('/:id',async(req,res,next)=>{try{const x=await db.get('SELECT * FROM expenses WHERE id=$1',[req.params.id]);if(!x)return res.status(404).json({error:'Expense not found.'});const b=req.body;const r=await db.get(`UPDATE expenses SET vendor_id=$1,category=$2,description=$3,date=$4,total_amount=$5,advance_paid=$6,settled_amount=$7,payment_mode=$8,bill_no=$9,notes=$10 WHERE id=$11 RETURNING *`,[b.vendor_id!==undefined?b.vendor_id:x.vendor_id,b.category??x.category,b.description??x.description,b.date??x.date,b.total_amount??x.total_amount,b.advance_paid??x.advance_paid,b.settled_amount??x.settled_amount,b.payment_mode??x.payment_mode,b.bill_no??x.bill_no,b.notes??x.notes,req.params.id]);res.json(withStatus(r))}catch(e){next(e)}});
router.delete('/:id',requireRole('admin'),async(req,res,next)=>{try{const r=await db.get('DELETE FROM expenses WHERE id=$1 RETURNING id',[req.params.id]);if(!r)return res.status(404).json({error:'Expense not found.'});res.json({success:true})}catch(e){next(e)}});
router.get('/meta/categories',async(req,res,next)=>{try{const defaults=['DJ & Sound','Tent & Decoration','Idols & Pooja Samagri','Food & Prasadam','Permissions & Others'];const used=(await db.all('SELECT DISTINCT category FROM expenses')).map(r=>r.category);res.json([...new Set([...defaults,...used])])}catch(e){next(e)}});
module.exports=router;
