require('dotenv').config();
const express=require('express');const cors=require('cors');const morgan=require('morgan');const {initDb,pool}=require('./db');
const authRoutes=require('./routes/auth');const donationRoutes=require('./routes/donations');const expenseRoutes=require('./routes/expenses');const vendorRoutes=require('./routes/vendors');const inventoryRoutes=require('./routes/inventory');const teamRoutes=require('./routes/team');const announcementRoutes=require('./routes/announcements');const eventPhaseRoutes=require('./routes/eventPhases');const settingsRoutes=require('./routes/settings');const dashboardRoutes=require('./routes/dashboard');
const app=express();app.use(cors());app.use(express.json());app.use(morgan('dev'));
app.get('/',(req,res)=>res.json({status:'ok',service:'ganesh-portal-backend',message:'Ganesh Chaturthi Portal API is running'}));app.get('/api/health',async(req,res)=>{try{await pool.query('SELECT 1');res.json({status:'ok',service:'ganesh-portal-backend',database:'postgresql'})}catch(e){res.status(503).json({status:'error',error:'Database unavailable'})}});
app.use('/api/auth',authRoutes);app.use('/api/donations',donationRoutes);app.use('/api/expenses',expenseRoutes);app.use('/api/vendors',vendorRoutes);app.use('/api/inventory',inventoryRoutes);app.use('/api/team',teamRoutes);app.use('/api/announcements',announcementRoutes);app.use('/api/event-phases',eventPhaseRoutes);app.use('/api/settings',settingsRoutes);app.use('/api/dashboard',dashboardRoutes);
app.use('/api',(req,res)=>res.status(404).json({error:'Not found.'}));app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Something went wrong on the server.'})});
const PORT=process.env.PORT||5000;
initDb().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log(`Ganesh Chaturthi Portal API running on port ${PORT}`))).catch(err=>{console.error('Database initialization failed:',err);process.exit(1)});
process.on('SIGTERM',async()=>{await pool.end();process.exit(0)});
